[package]
name = "url-parse"
version = "0.5.7"
edition = "2021"
description = "🔗 A Rust library for parsing URLs."
license = "MIT"
repository = "https://github.com/mihaigalos/url-parse"
categories = ["parser-implementations", "web-programming", "encoding"]

[dependencies]
regex = "1.6.0"
