[package]
name = "url-parse"
version = "0.1.2"
edition = "2021"
description = "🔗 A Rust library for parsing URLs."
license = "MIT"
repository = "https://github.com/mihaigalos/url-parse"
categories = ["parser-implementations", "web-programming", "encoding"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
regex = "1.5.6"