name: CI

on:
  push:
    paths-ignore:
      - '*.md'
      - 'screenshots/**'
    branches: [ main ]
  pull_request:
    paths-ignore:
      - '*.md'
      - 'screenshots/**'
    branches: [ main ]

  workflow_dispatch: # Run with Run Workflow button in GitHub Action Job, set debug_enabled=true for interactive ssh session.
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'     
        required: false
        default: false
env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: docker://agilepathway/pull-request-label-checker:latest
      with:
        none_of: wip
        repo_token: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name == 'pull_request'

    - uses: actions/checkout@v3

    - uses: extractions/setup-just@v1
      with:
        just-version: 0.10.2  # optional semver specification, otherwise latest

    - name: Cargo Cache
      uses: actions/cache@v3
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}
          ${{ runner.os }}-cargo

    - name: Cargo Target Cache
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-cargo-target-${{ hashFiles('Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-cargo-target-${{ hashFiles('Cargo.toml') }}
          ${{ runner.os }}-cargo-target

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}

    - name: Run tests
      run: |
        cargo test

  clippy:
    runs-on: ubuntu-latest
    steps:

    - uses: docker://agilepathway/pull-request-label-checker:latest
      with:
        none_of: wip
        repo_token: ${{ secrets.GITHUB_TOKEN }}
      if: github.event_name == 'pull_request'

    - uses: actions/checkout@v3

    - name: Cargo Cache
      uses: actions/cache@v3
      with:
        path: ~/.cargo
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ hashFiles('Cargo.toml') }}
          ${{ runner.os }}-cargo
    - name: Cargo Target Cache
      uses: actions/cache@v3
      with:
        path: target
        key: ${{ runner.os }}-cargo-target-${{ hashFiles('Cargo.toml') }}
        restore-keys: |
          ${{ runner.os }}-cargo-target-${{ hashFiles('Cargo.toml') }}
          ${{ runner.os }}-cargo-target
    - name: Run cargo-clippy
      run: |
        cargo clippy

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 30

      - uses: extractions/setup-just@v1
        with:
          just-version: 0.10.2  # optional semver specification, otherwise latest
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run cargo-tarpaulin
        uses: actions-rs/tarpaulin@v0.1
        with:
          version: '0.20.1'
          args: '-- --test-threads 1'
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3.1.0
        with:
          token: ${{secrets.CODECOV_TOKEN}}

      - name: Archive code coverage results
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: cobertura.xml 
          repo-token: ${{ secrets.GITHUB_TOKEN }}
